# Generated by Django 5.2.1 on 2025-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
    ]
