# Generated by Django 5.2.1 on 2025-05-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_userprogress_course_name'),
        ('users', '0004_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProgress',
            new_name='Progress',
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
